apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  #TODO: Change to an actual JWT value
  JWT_SECRET: dGVzdDEyMw==