apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
      - name: {{ .Release.Name }}-backend
        envFrom:
          - configMapRef:
            name: backend-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET
        # TODO get image repository from values.yaml
        image: localhost:32000/vu_sc_backend
        imagePullPolicy: Always # Ensure that updated images are applied
        ports:
        - containerPort: {{ .Values.backendPort }}
