apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.backendPort }}
    targetPort: {{ .Values.backendPort }}
  selector:
    app: {{ .Release.Name }}-backend