apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
      - name: {{ .Release.Name }}-frontend
        # TODO get image repository from values.yaml
        image: localhost:32000/vu_sc_frontend
        imagePullPolicy: Always # Ensure that updated images are applied
        ports:
        - containerPort: {{ .Values.frontendPort }}
