# NOTE keep in sync with `mongodb.global.namespaceOverride`
namespace: development
registry: localhost:32000
replicaCount: 2
backendImageTag: latest
backendPort: 3000
frontendImageTag: latest
frontendPort: 3001
databasePort: 27017

# Subchart values
mongodb:
  global:
    # NOTE keep in sync with `namespace`
    namespaceOverride: development
  auth:
    enabled: false
  nameOverride: database
